name: Run Python Scripts on PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run all Python files in root and feature1/
      run: |
        echo "Running Python scripts in root and feature1/"
        for file in ./*.py feature1/*.py; do
          if [ -f "$file" ]; then
            echo "Running $file"
            python "$file"
          fi
        done
